[build]
command = "npm install && npm install --prefix delivery-form-frontend && npm run --prefix delivery-form-frontend build"
publish = "delivery-form-frontend/build"
functions = "netlify/functions"

[functions]
node_bundler = "esbuild"

